- name: Päivitä apt cache
  apt:
    update_cache: yes

- name: Päivitä kaikki paketit
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name : Asennat peruspaketit
  apt: 
    name:
      - curl
      - micro
      - bash-completion
      - tree
      - git
      - wget
    state: present
